In [1]:
import pandas as pd
data_dict = {
'Head': [3395.857, 3799.656, 3586.294, 3297.862, 3589.723, 3845.345, 3071.78, 4281.716, 3911.758, 3303.01, 3681.682, 3839.803, 3407.191, 3644.213, 3454.245, 3980.208, 3175.041, 4079.583, 3562.681, 3343.571, 3173.546, 3833.179, 3634.262, 3629.812, 3438.011, 3586.802, 3223.428, 3384.209, 3747.829, 3816.94, 3721.915, 3702.461, 4200.341, 3570.801, 3595.321, 3259.224, 3303.776, 3614.819, 3642.664, 3515.177]
,'Age': [0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0]
,'Sex': [0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0]
,'Brain': [1285.719, 1268.747, 1340.691, 1130.687, 1273.834, 1390.031, 1080.863, 1439.722, 1433.383, 1108.224, 1410.731, 1327.043, 1302.406, 1315.217, 1283.354, 1281.671, 1324.262, 1388.247, 1386.904, 1286.05, 1110.415, 1266.181, 1232.842, 1237.006, 1212.072, 1254.097, 1150.887, 1282.197, 1322.598, 1295.226, 1407.769, 1321.068, 1340.529, 1217.902, 1259.377, 1240.106, 1229.781, 1316.603, 1344.734, 1255.443]}

In [3]:
df=pd.DataFrame(data_dict)

In [9]:
df

        Head  Age  Sex     Brain
0   3395.857    0    0  1285.719
1   3799.656    0    0  1268.747
2   3586.294    0    0  1340.691
3   3297.862    1    1  1130.687
4   3589.723    0    1  1273.834
5   3845.345    0    1  1390.031
6   3071.780    1    1  1080.863
7   4281.716    1    1  1439.722
8   3911.758    1    0  1433.383
9   3303.010    0    1  1108.224
10  3681.682    0    0  1410.731
11  3839.803    1    0  1327.043
12  3407.191    1    0  1302.406
13  3644.213    0    0  1315.217
14  3454.245    0    1  1283.354
15  3980.208    1    1  1281.671
16  3175.041    0    0  1324.262
17  4079.583    0    0  1388.247
18  3562.681    1    1  1386.904
19  3343.571    0    0  1286.050
20  3173.546    1    1  1110.415
21  3833.179    1    0  1266.181
22  3634.262    1    1  1232.842
23  3629.812    1    1  1237.006
24  3438.011    0    1  1212.072
25  3586.802    0    1  1254.097
26  3223.428    1    0  1150.887
27  3384.209    0    0  1282.197
28  3747.829    1    1  1322.598
29  3816.940    0    1  1295.226
30  3721.915    0    0  1407.769
31  3702.461    1    0  1321.068
32  4200.341    1    1  1340.529
33  3570.801    1    1  1217.902
34  3595.321    1    0  1259.377
35  3259.224    1    0  1240.106
36  3303.776    1    0  1229.781
37  3614.819    0    1  1316.603
38  3642.664    0    1  1344.734
39  3515.177    0    0  1255.443

In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(np.array(df['Head']).reshape((-1, 1)), np.array(df['Brain']))
y_predict = model.predict(np.array(3450).reshape(-1,1))
y = 1386.2
residual = abs(y_predict - y).round(1)
residual

In [24]:
0.64

array([133.9])

In [16]:
model.predict(np.array(3450).reshape(-1,1))-1386.2

array([-133.94666089])

In [10]:
df['Head']

0     3395.857
1     3799.656
2     3586.294
3     3297.862
4     3589.723
5     3845.345
6     3071.780
7     4281.716
8     3911.758
9     3303.010
10    3681.682
11    3839.803
12    3407.191
13    3644.213
14    3454.245
15    3980.208
16    3175.041
17    4079.583
18    3562.681
19    3343.571
20    3173.546
21    3833.179
22    3634.262
23    3629.812
24    3438.011
25    3586.802
26    3223.428
27    3384.209
28    3747.829
29    3816.940
30    3721.915
31    3702.461
32    4200.341
33    3570.801
34    3595.321
35    3259.224
36    3303.776
37    3614.819
38    3642.664
39    3515.177
Name: Head, dtype: float64